# TP5 :  introduction au traitement d'image avec NumPy 

---
## 1. Caractéristique d'un fichier d'image PNG et format de codage RVBA

*PNG est particulièrement approprié lorsqu’il s’agit d’enregistrer des images synthétiques destinées au Web comme des graphiques, des icônes, des images représentant du texte (bonne conservation de la lisibilité), ou des images avec des dégradés. Le PNG surpasse régulièrement le format GIF en ce qui concerne la réduction de la taille des fichiers (avec une palette de couleurs bien choisie) ou la qualité (puisqu’il n’est pas limité à 256 couleurs). (source wikipédia)*

Le format que l'on utilisera est PNG en « couleurs vraies » où le codage des pixels sera au **format RVBA** : 

Le format RVBA (rouge, vert, bleu, alpha) est un format couramment utilisé pour coder les couleurs des pixels dans une image numérique.

Chaque pixel est codé sur quatre octets (8 bits chacun) pour stocker les valeurs de rouge (R), vert (V), bleu (B) et alpha (transparence) pour chaque pixel. 

Les valeurs de rouge, vert et bleu peuvent varier de 0 à 255, ce qui permet de représenter plus de 16 millions de couleurs différentes ($256^3=2^{24}$). On utilise la synthèse additive des couleurs : le triplet (0, 0, 0) correspond à un pixel noir alors qu’un pixel blanc est donné par (255, 255, 255). Un pixel « pur rouge » est codé par (255, 0, 0).

La valeur alpha peut varier de 0 (transparent) à 255 (opaque) et permet de spécifier la transparence d'un pixel. 

En utilisant ces quatre canaux de couleur, RVBA permet de créer des images riches en couleurs et en détails.
La présence d’un canal alpha définissant différents niveaux de transparence le rend idéal pour la composition sur les pages web. Cette caractéristique est bien implémentée par la majorité des navigateurs web. 


---
## 2. Ouverture d'un fichier PNG

Pour ouvrir un fichier PNG on pourra utiliser le sous-module **Image** de la bibliothèque **pillow** (`from PIL import Image`). 

La fonction `open()` du module Image retourne un objet PIL de type image. 

A partir de cet objet il est possible de réaliser un certain nombre d'opérations :
* **show()** : fonction affichant l'objet image

* **width** : attribut contenant la largeur de l'image en pixels

* **height** : attribut contenant la hauteur de l'image en pixels

* **mode** : attribut contenant le mode de codage de l'image :  
    * "1" pour les images en noir et blanc.
    * "L" pour les images en niveaux de gris.
    * "P" pour les images indexées.
    * "RGB" pour les images couleur avec des composantes rouge, verte et bleue.
    * "RGBA" pour les images couleur avec des composantes rouge, verte et bleue et un canal alpha
    * "CMYK" pour les images en mode cyan, magenta, jaune et noir.


In [3]:
# installation du module PIL si necessaire : 
# pip install pillow

# importation du sous-module Image du module PIL
from PIL import Image 

# Ouverture/Chargement de l'image dans un objet PIL de type Image
image = Image.open("santa-claus.png") 

# Information sur l'image 
print(type(image))
print("Taille de l'image en pixel", image.height,"x",image.width)
print(image.mode)

# affichage de l'image
image.show()

<class 'PIL.PngImagePlugin.PngImageFile'>
Taille de l'image en pixel 948 x 730
RGBA


----
## 3. Récupération de l'image sous la forme d'un tableau 3D

In [4]:
# !pip3 install numpy
import numpy as np

La séquence Python `ìmageTab = np.array(image)`  récupére la liste des pixel de l'image sous la forme d'un tableau ndarray : 

In [3]:
imageTab=np.array(image)

##### **Question 1 :** Vérifiez que ce tableau est *tri-dimensionnel* de taille $h \times l \times 4 $ où 
* $h$ est la hauteur de l’image en nombre de pixel 
* $l$ sa largeur en nombre de pixel 
* 4 sa profondeur correspondant aux 4 canaux : R, G, B et le canal alpha. 

et affichez-le

In [4]:
# réponse :
if imageTab.shape[0]==image.height and imageTab.shape[1]==image.width and imageTab.shape[2]==4:
    print("La taille est bonne")
else :
    print("La taille n'est pas bonne")


La taille est bonne


##### **Question 2 :** Extraire dans une variable R le sous-tableau 2D correspondant au canal rouge. Vérifiez sa dimension.

In [5]:
print(imageTab)

[[[255 255 255   0]
  [255 255 255   0]
  [255 255 255   0]
  ...
  [255 255 255   0]
  [255 255 255   0]
  [255 255 255   0]]

 [[255 255 255   0]
  [255 255 255   0]
  [255 255 255   0]
  ...
  [255 255 255   0]
  [255 255 255   0]
  [255 255 255   0]]

 [[255 255 255   0]
  [255 255 255   0]
  [255 255 255   0]
  ...
  [255 255 255   0]
  [255 255 255   0]
  [255 255 255   0]]

 ...

 [[255 255 255   0]
  [255 255 255   0]
  [255 255 255   0]
  ...
  [255 255 255   0]
  [255 255 255   0]
  [255 255 255   0]]

 [[255 255 255   0]
  [255 255 255   0]
  [255 255 255   0]
  ...
  [255 255 255   0]
  [255 255 255   0]
  [255 255 255   0]]

 [[255 255 255   0]
  [255 255 255   0]
  [255 255 255   0]
  ...
  [255 255 255   0]
  [255 255 255   0]
  [255 255 255   0]]]


In [6]:
# réponse
R = np.array([[rvb[0] for rvb in colone] for colone in imageTab])
R1 = imageTab[::,::,0]
R1

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

##### **Question 3 :** Choisir un pixel particulier et affichez son codage 

In [7]:
# réponse
def getPixel(ImageArray, x, y):
    return ImageArray[x][y]

getPixel(imageTab, 500, 500)

array([241, 241, 241, 255], dtype=uint8)

----
## 4. Modifications de l'image

Dans la suite, on va jouer avec les images en les modifiant. Pour cela, il suffit de modifier le tableau ndarray associé
(ou d’en créer un nouveau). Voyons comment obtenir une image à partir d’un tableau ndarray :

```python
# tab est un tableau ndarray 3D
nouvelle_image=Image.fromarray(tab)

# pour afficher l'image
nouvelle_image.show() 

# pour l'enregistrer au format voulu
nouvelle_image.save("nom_de_la_nouvelle_image.png") 
```


Le tableau tab doit être composé d’éléments uint8 (c’est-à-dire d’entiers non signés codés sur 8 bits,
soit entre 0 et 255). Si ce n’est pas le cas (flottants, entiers codées sur 32 bits...), un message d’erreur comme
`TypeError: Cannot handle this data type` s’affiche. 


Pour créer de nouvelles images, on procédera de deux façons :
* en modifiant un tableau Numpy obtenu à partir d’une image : le tableau a déja le bon type ;

* en créant un nouveau tableau pour le remplir. Dans ce cas, il faudra veiller à ce que le tableau ait le bon type :
 Par exemple, on peut créer un tableau de zéros avec 
 
 `np.zeros((h, l, 4), dtype="uint8")`

##### **Qestion 4  : conversion en une image blanche**

Ecrivez une fonction `image_blanche()` qui affiche, à partir d'une image PIL donnée en argument, une image blanche de même dimension. 

Il suffira de mettre, pour tous les pixels, les 4 composantes à 255.

In [8]:
# réponse : 
def image_blanche(image):
    imageTab=np.array(image)
    h,l,r=imageTab.shape 
    # à compléter
    for x in range(h):
        for y in range(l):
                imageTab[x][y] = [255, 255, 255, 255]



    return Image.fromarray(imageTab)# à compléter


In [9]:
# test 
image=Image.open("santa-claus.png")
image_blanc=image_blanche(image)
image_blanc.save("C:\\Users\Kevin\santa-clauss-blanc.png")

# visualisation de l'image 
# prb d'affichage sur les machines des salles TP 
# à décommenter si ordinateur personnel
image_blanc.show()

##### **Question 5 : extraire la composante bleu**
Ecrire une fonction `composante_bleu()` retournant l’image PIL passée en paramètre en nuance de bleu.

En travaillant sur le tableau associé à l’image, il s’agit simplement de mettre à 0 les composantes R et V des pixels

In [8]:
# réponse
def composante_bleu(image):
    # à compléter
    imageTab=np.array(image)
    h,l,r=imageTab.shape
    for x in range(h):
        for y in range(l):
            imageTab[x][y][0] = 0
            imageTab[x][y][1] = 0
    return Image.fromarray(imageTab)



    

In [9]:
# test sur l'image du fichier santa-clauss.png
# test 
image=Image.open("santa-claus.png")
image_bleu=composante_bleu(image)
image_bleu.save("santa-clauss-bleu.png")

# visualisation de l'image 
# prb d'affichage sur les machines des salles TP 
# à décommenter si ordinateur personnel
image_bleu.show()



##### **Question 6 :  conversion d'une image en niveaux de gris**

Ecrire une fonction `conversionGris()` retournant l'image PIL passée en paramètre en niveaux de gris. 

La formule couramment utilisée pour convertir une image en niveaux de gris est de prendre la moyenne des valeurs de rouge, vert et bleu (R, V, B) des pixels. Cette formule est donnée par : $$(R + V + B) / 3$$

Il est également possible d'utiliser une formule basée sur la luminosité humaine, qui tient compte de la façon dont l'œil humain perçoit la luminosité des couleurs. Cette formule est donnée par :

$$0.2126 * R + 0.7152 * V + 0.0722 * B$$

Cela a pour effet de donner plus de poids aux composantes vertes, qui sont celles qui ont le plus d'influence sur la luminosité perçue par l'œil humain.

Si le codale est au format RVBA, la composante alpha (A) qui est l'opacité ne change pas la formule pour passer en niveau de gris, on utilise toujours la moyenne ou la formule basée sur la luminosité humaine.

In [5]:
# réponse
def conversionGrisOeil(image):
    # à compléter
    imageTab=np.array(image)
    h,l,r=imageTab.shape
    for x in range(h):
        for y in range(l):
            imageTab[x][y][0] *= 0.2126
            imageTab[x][y][1] *= 0.7152
            imageTab[x][y][2] *= 0.0722
    return Image.fromarray(imageTab)

def conversionGrisMoy(image):
    # à compléter
    imageTab=np.array(image)
    h,l,r=imageTab.shape
    for x in range(h):
        for y in range(l):
            r, v, b, a = imageTab[x][y]
            imageTab[x][y][0] = (r+v+b)/3
            imageTab[x][y][1] = (r+v+b)/3
            imageTab[x][y][2] = (r+v+b)/3
    return Image.fromarray(imageTab)



In [7]:
# test sur l'image du fichier santa-clauss.png
image = Image.open("santa-claus.png") 
image_gris=conversionGrisOeil(image)
image_gris.save("santa-clauss-gris.png")

# visualisation de l'image
# prb d'affichage sur les machines des salles TP 
# à décommenter si ordinateur personnel
image_gris.show()

##### **Question 7 : basculement**

Ecrivez une fonction `basculement()` qui, à partir d'une image PIL comme argument, affiche l'image "basculée" par transposition de la matrice. 

On utilisera la fonction `np.transpose()` qui transpose une matrice (tableau 2D uniquement) : il faudra donc l'appliquer sur chaque tableau 2D des différents canaux...

In [73]:
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Returns an array with axes transposed.
    
    For a 1-D array, this returns an unchanged view of the original array, as a
    transposed vector is simply the same vector.
    To convert a 1-D array into a 2-D column vector, an additional dimension
    must be added, e.g., ``np.atleast2d(a).T`` achieves this, as does
    ``a[:, np.newaxis]``.
    For a 2-D array, this is the standard matrix transpose.
    For an n-D array, if axes are given, their order indicates how the
    axes are permuted (see Examples). If axes are not provided, then
    ``transpose(a).shape == a.shape[::-1]``.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : tuple or list of ints, optional
        If specified, it must be a tuple or list which contains a permutation
        of [0,1,...,N-1] where N is the number of axes of `a`. The `i`'th axis
        of the returned array will correspond to the axis num

In [13]:
# réponse
def basculement(image):
    # à compléter
    imageTab=np.array(image)
    transpose = np.transpose(imageTab, (1,0,2))
    return Image.fromarray(transpose)

In [14]:
# test sur l'image du fichier santa-clauss.png
image = Image.open("santa-claus.png")
# image.show() #affichage
image_transpose=basculement(image)
print(image_transpose)
image_transpose.save("santa-clauss-transpose.png")

# visualisation de l'image 
# prb d'affichage sur les machines des salles TP 
# à décommenter si ordinateur personnel
image_transpose.show() #affichage


<PIL.Image.Image image mode=RGBA size=948x730 at 0x2309A29FFD0>


-----
